version: '3.8'
services:
  postgres:
    image: postgres:13 # Versión compatible con M1
    container_name: gym_db_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gymdb
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
